"use client";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import HomeSearchBox from "@/components/HomeSearchBox";
import { useRouter } from "next/router";
import Link from "next/link";
import useTranslation from "next-translate/useTranslation";
import type { NextPage } from "next";
import NavBar from "@/components/NavBar";

type HomePage<P = {}> = NextPage<P> & {
  getLayout?: (page: JSX.Element) => JSX.Element;
};

const Home: HomePage = () => {
  const { locale, locales, push } = useRouter();
  const { t, lang } = useTranslation("home");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="container">
          <div
            style={{
              width: "100%",
              height: "100%",
              position: "fixed",
              left: 0,
              top: 0,
            }}
          ></div>
          <HomeSearchBox />
        </div>
      </div>
    </>
  );
};

Home.getLayout = (page: JSX.Element) => {
  return (
    <>
      <NavBar {...page.props} />
      {page}
    </>
  );
};

export default Home;
// export const getStaticProps: GetStaticProps = async ({ locale }) => {
//   console.log(locale, ">");
//   return {
//     props: {
//       ...(await serverSideTranslations(locale ? locale : "", ["common"])),
//     },
//   };
// };
