"use client";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import ServicesSearchBox from "@/components/ServicesSearchBox";
import { useRouter } from "next/router";
import Link from "next/link";
import useTranslation from "next-translate/useTranslation";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { locale, locales, push } = useRouter();
  const { t, lang } = useTranslation("home");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="container">
          <ServicesSearchBox />
        </div>
      </div>
    </>
  );
}

// export const getStaticProps: GetStaticProps = async ({ locale }) => {
//   console.log(locale, ">");
//   return {
//     props: {
//       ...(await serverSideTranslations(locale ? locale : "", ["common"])),
//     },
//   };
// };
